const app = document.querySelector('#app');

const button = (label, href, light = false) => `<a class="btn${light ? ' light' : ''}" href="${href}">${label}<span>↗</span></a>`;
const header = (kicker, title, copy) => `<div class="eyebrow">${kicker}</div><h1 class="display page-title">${title}</h1>${copy ? `<p class="lede">${copy}</p>` : ''}`;
const artOne = 'assets/photo_2026-09-01_13-54-05.jpg';
const artTwo = 'assets/photo_2026-09-01_13-54-37.jpg';

function home() {
  return `<section class="page hero">
    <div class="eyebrow">Kurogami presents / 001</div>
    <h1 class="display">GAMI<br>BOYZ</h1>
    <p class="hero-sub"><span>Brotherhood lane</span> of the movement</p>
    <div class="btns">${button('Enter the Club', '#/club')}${button('Get Access', '#/access', true)}</div>
    <div class="hero-art" aria-hidden="true"><img src="${artOne}" alt="Illustrated fragmented character with a chain and glitch cuts" /><i class="glitch a"></i><i class="glitch b"></i><i class="glitch c"></i></div>
  </section>
  <div class="ticker"><span>NOT FOR SPECTATORS <b>✦</b> GAMI BOYZ MOVE TOGETHER <b>✦</b> CLUB FIRST. NOISE LATER <b>✦</b> </span></div>
  <section class="page cream-band"><div class="split"><div><div class="section-label"><span>01 / What it is</span><span>GB-000</span></div><h2 class="display" style="font-size:clamp(64px,10vw,130px);margin:30px 0 0">Brotherhood<br>over branding.</h2></div><div><p class="body-copy">A raw cultural brotherhood lane for operators and movers. We build signal, pull up in person, and keep the circle tight.</p><p class="body-copy">No performance theater. No spectators. Just access, loyalty, and motion.</p>${button('Meet the Boyz', '#/club', true)}</div></div></section>
  <section class="page"><div class="section-label"><span>02 / The marks</span><span>Symbols in rotation</span></div><div class="symbol-row"><div class="symbol"><div class="pyramid"></div></div><div class="symbol"><b class="hand">☝</b></div><div class="symbol"><b class="chain-symbol">∞</b></div><div class="symbol"><b>◎</b></div></div></section>
  <section class="page cream-band"><div class="section-label"><span>03 / Access snapshot</span><span>Earn your way in</span></div><div class="index-grid"><div class="index-card"><strong>01</strong><p>Find the signal</p></div><div class="index-card"><strong>02</strong><p>Show up</p></div><div class="index-card"><strong>03</strong><p>Move with the club</p></div><div class="index-card"><strong>04</strong><p>Keep it locked</p></div></div></section>
  <section class="page"><div class="section-label"><span>04 / Field notes</span><a href="#/gallery">View all ↗</a></div><div class="art-grid"><div class="art-panel tall"><img src="${artOne}" alt="Fragmented illustrated character artwork" /><span class="art-note">GB / 001</span><b class="art-type">EYE<br>ON</b></div><div class="art-panel"><img src="${artTwo}" alt="Pyramid and all-seeing eye illustration" /><span class="art-note">Symbol / 02</span><b class="art-type">LINK</b></div><div class="art-panel"><img src="${artOne}" alt="Cropped character detail" /><span class="art-note">Fragment / 03</span><b class="art-type">RAW</b></div></div></section>
  <section class="page cream-band"><div class="split"><div><div class="eyebrow">Last call</div><h2 class="display" style="font-size:clamp(70px,12vw,160px);margin:25px 0">GET IN<br>FORMATION.</h2></div><div><p class="lede">Access is earned. The request window is open.</p>${button('Request Access', '#/join')}</div></div></section>`;
}

function club() { return `<section class="page">${header('Inside / GB club', 'The Boyz', 'This is the brotherhood room. Culture, loyalty, and motion over performance theater.')}<div class="cards"><article class="feature-card"><span class="number">01</span><h3>Operators</h3><p>People who make the move before the room catches up.</p></article><article class="feature-card"><span class="number">02</span><h3>Creators</h3><p>Artists, builders, tastemakers. The ones making the signal louder.</p></article><article class="feature-card"><span class="number">03</span><h3>Street-to-<br>finance movers</h3><p>Cultural fluency with an operator's instinct.</p></article><article class="feature-card"><span class="number">04</span><h3>Presence</h3><p>Club events, pop-ups, and showing up in real life.</p></article></div></section><div class="ticker"><span>GAMI BOYZ MOVE TOGETHER <b>✦</b> CULTURE IS THE CURRENCY <b>✦</b> </span></div>`; }
function access() { return `<section class="page">${header('Threshold / 002', 'Access', 'A key to the room. Membership is simple: show signal, hold the line, move with the club.')}<div class="tier-grid"><article class="tier"><h3>Runner</h3><p>You're on the radar. Get the signal and find your way to the room.</p><span class="eyebrow">Entry / Signal</span></article><article class="tier"><h3>Boyz</h3><p>Core membership. Club access, drops, events, and the full transmission.</p><span class="eyebrow">Entry / Member</span></article><article class="tier"><h3>Inner Circle</h3><p>For the ones moving the room forward. Invite only. Keep it locked.</p><span class="eyebrow">Entry / Invite</span></article></div><div class="panel dark"><h2>Access is earned.</h2><p>Hold-to-enter access may connect to a token or club key when the rail is live. No shortcuts. No guarantees.</p>${button('Request Access', '#/join')}</div></section>`; }
function gallery() { return `<section class="page">${header('Visual archive / 003', 'Gallery', 'Cut-ups from the movement. Red signal, black ink, living symbols.')}<div class="art-grid"><div class="art-panel tall"><img src="${artOne}" alt="Fragmented illustrated character with glitch cuts" /><span class="art-note">Character study / 01</span><b class="art-type">EYE<br>ON</b></div><div class="art-panel"><img src="${artTwo}" alt="Pyramid, clouds, hand, and all-seeing eye" /><span class="art-note">Chain language</span><b class="art-type">LINK</b></div><div class="art-panel"><img src="${artOne}" alt="Cropped illustrated face detail" /><span class="art-note">Street myth / 03</span><b class="art-type">RAW</b></div><div class="art-panel"><img src="${artTwo}" alt="Cropped pyramid-eye artwork" /><span class="art-note">Signal / 04</span><b class="art-type">GB</b></div><div class="art-panel"><img src="${artOne}" alt="Cropped illustrated body fragment" /><span class="art-note">No spectators</span><b class="art-type">MOVE</b></div><div class="art-panel"><img src="${artTwo}" alt="Pyramid study artwork" /><span class="art-note">Pyramid study</span><b class="art-type">▲</b></div></div></section>`; }
function token() { return `<section class="page">${header('Token rail / 004', 'Token', 'No live token is being claimed here. When the rail is real, the official signal will land in this room first.')}<div class="panel dark"><div class="eyebrow">Status / Coming</div><h2>Token rail coming.</h2><p>There is no official contract address or buy link to share right now. Ignore fake Gami Boyz tokens, DMs, and promises of returns.</p><div class="btns">${button('Back to Club', '#/club', true)}</div></div></section>`; }
function join() { return `<section class="page"><div class="split">${header('Request / 005', 'Join', 'Tell us who you are. Club access is selective.') }<form class="form" id="join-form"><label>Name / handle<input name="name" required placeholder="your signal" /></label><label>Telegram / IG<input name="social" required placeholder="@handle" /></label><label>City<input name="city" placeholder="where you move" /></label><label>Why do you want in?<textarea name="why" required placeholder="keep it real"></textarea></label><label>Proof / ref note <span>(optional)</span><input name="proof" placeholder="who can vouch?" /></label><button class="btn" type="submit">Send Request <span>↗</span></button></form><div class="panel success" id="join-success"><div class="eyebrow">Transmission received</div><h2>Request received.</h2><p>Club access is selective. Watch your signal.</p></div></div></section>`; }
function members() { return `<section class="page"><div class="gate"><div class="eyebrow">Private room / 006</div><h1 class="display" style="font-size:clamp(85px,17vw,180px);margin:30px 0">Members<br>only.</h1><p class="lede">Password gate placeholder. The room opens when the signal is right.</p><form class="form" id="gate-form"><label>Club key<input type="password" placeholder="enter key" required /></label><button class="btn" type="submit">Enter Room <span>↗</span></button></form><div class="panel dark" id="member-room" style="display:none"><h2>Welcome inside.</h2><div class="announcement"><strong>Announcements</strong><small>Next transmission pending</small></div><div class="announcement"><strong>Art drops</strong><small>Archive / Locked</small></div><p>Access status: <b>Boyz / active</b></p></div></div></section>`; }

const routes = { '/':home, '/club':club, '/access':access, '/gallery':gallery, '/token':token, '/join':join, '/members':members };
function render() { const path = window.location.hash.replace('#','') || '/'; document.body.dataset.route = path === '/' ? 'home' : path.slice(1); app.innerHTML = (routes[path] || home)(); app.focus(); window.scrollTo(0,0); bindForms(); }
function bindForms() { const form = document.querySelector('#join-form'); if (form) form.addEventListener('submit', event => { event.preventDefault(); form.style.display='none'; document.querySelector('#join-success').classList.add('show'); }); const gate = document.querySelector('#gate-form'); if (gate) gate.addEventListener('submit', event => { event.preventDefault(); gate.style.display='none'; document.querySelector('#member-room').style.display='block'; }); }
window.addEventListener('hashchange', render); render();
