const app = document.querySelector('#app');

const button = (label, href, light = false) => `<a class="btn${light ? ' light' : ''}" href="${href}">${label}<span>↗</span></a>`;
const header = (kicker, title, copy) => `<div class="eyebrow">${kicker}</div><h1 class="display page-title">${title}</h1>${copy ? `<p class="lede">${copy}</p>` : ''}`;
const artOne = 'assets/photo_2026-09-01_13-54-05.jpg';
const artTwo = 'assets/photo_2026-09-01_13-54-37.jpg';
const artistInstagram = 'https://www.instagram.com/tokeyodraws?stkn=MXkxYTR4ZHZnOGtoMA==';
const galleryAssets = [
  ['photo_2026-09-01_13-54-05.jpg', 'Fragmented illustrated character artwork', 'GB / 001', 'EYE<br>ON'],
  ['photo_2026-09-01_13-54-37.jpg', 'Illustrated character portrait', 'Signal / 02', 'MOVE'],
  ['photo_2026-09-01_21-39-09.jpg', 'Illustrated food still life', 'No spectators / 03', 'TABLE'],
  ['photo_2026-09-01_21-39-18.jpg', 'Split portrait illustration', 'Street myth / 04', 'FORM'],
  ['photo_2026-09-01_21-39-35.jpg', 'Illustrated character composition', 'Study / 05', 'RAW'],
  ['photo_2026-09-01_21-39-45.jpg', 'Illustrated culture composition', 'Culture / 06', 'LINK'],
  ['photo_2026-09-01_21-39-56.jpg', 'Illustrated pink character', 'Character study / 07', 'PINK'],
  ['photo_2026-09-01_21-40-04.jpg', 'Illustrated character artwork', 'Signal / 08', 'LOOK'],
  ['photo_2026-09-01_21-40-42.jpg', 'Illustrated portrait close-up', 'Portrait / 09', 'FORM'],
  ['photo_2026-09-01_21-40-50.jpg', 'Illustrated food and culture scene', 'Table / 10', 'MOVE'],
  ['photo_2026-09-01_21-41-02.jpg', 'Illustrated movement study', 'World / 11', 'RAW'],
  ['photo_2026-09-01_21-41-12.jpg', 'Illustrated symbol composition', 'Signal / 12', 'EYE'],
  ['photo_2026-09-01_21-41-23.jpg', 'Illustrated landscape emblem', 'World / 13', '▲'],
  ['photo_2026-09-01_21-41-53.jpg', 'Red masked illustrated figure', 'Chain language / 14', 'LINK'],
  ['photo_2026-09-01_21-42-02.jpg', 'Illustrated character study', 'Character study / 15', 'FORM']
];

function homeGallery() { return `<section class="page"><div class="section-label"><span>07 / Gallery</span><a href="#/gallery">View all ↗</a></div><div class="art-grid">${galleryAssets.map((image, index) => `<div class="art-panel${index === 0 ? ' tall' : ''}"><img src="assets/${image[0]}" alt="${image[1]}" /><span class="art-note">${image[2]}</span><b class="art-type">${image[3]}</b></div>`).join('')}</div></section>`; }

function home() {
  return `<section class="page hero">
    <div class="eyebrow">Kurogami presents / 001</div>
    <h1 class="display">GAMI<br>BOYZ</h1>
    <p class="hero-sub"><span>Brotherhood lane</span> of the movement</p>
    <div class="hero-network-copy"><strong>Culture x Finance.</strong><br>A trading-led operator network for the new economy.<small>The NFT is the key. The network is the value.</small></div>
    <div class="btns">${button('Enter the Club', '#/club')}${button('Get Access', '#/access', true)}</div>
    <div class="hero-art" aria-hidden="true"><img src="${artOne}" alt="Illustrated fragmented character with a chain and glitch cuts" /><i class="glitch a"></i><i class="glitch b"></i><i class="glitch c"></i></div>
  </section>
  <div class="ticker"><span>NOT FOR SPECTATORS <b>✦</b> GAMI BOYZ MOVE TOGETHER <b>✦</b> CLUB FIRST. NOISE LATER <b>✦</b> </span></div>
  <section class="page cream-band"><div class="split"><div><div class="section-label"><span>01 / What it is</span><span>GB-000</span></div><h2 class="display" style="font-size:clamp(64px,10vw,130px);margin:30px 0 0">Brotherhood<br>with a rail.</h2></div><div><p class="body-copy"><strong>Gami Boyz is the operator brotherhood inside Kurogami.</strong></p><p class="body-copy">Kurogami is an operator network for the new economy. You do not just buy a token and hope. You get access to trading edge, structured opportunities, incubation, and exposure to higher-level deals as the system grows.</p><p class="body-copy">The NFT is the key. Everything else is what the key opens.</p>${button('Meet the Boyz', '#/club', true)}</div></div></section>
  <section class="page home-desks"><div class="section-label"><span>02 / Trading desks</span><span>Two systems / one standard</span></div><h2 class="display home-section-title">The Desks</h2><div class="cards desk-cards"><article class="feature-card"><span class="number">DESK / 01</span><h3>Day Desk</h3><strong>Precision extraction.</strong><p>FX, metals, oil, structured setups.</p><p>Process, risk, execution.</p></article><article class="feature-card"><span class="number">DESK / 02</span><h3>Meme Desk</h3><strong>Positioning and narrative markets.</strong><p>Tiering, invalidations, structured entries.</p><p>Process over impulse.</p></article></div><p class="desk-line">One desk extracts. One desk positions. Both feed the network.</p></section>
  <section class="page cream-band"><div class="section-label"><span>03 / Why it matters</span><span>Keep it short</span></div><div class="index-grid why-grid"><div class="index-card"><strong>01</strong><p>Trading edge</p></div><div class="index-card"><strong>02</strong><p>Direction / alpha</p></div><div class="index-card"><strong>03</strong><p>Incubation</p></div><div class="index-card"><strong>04</strong><p>New economy exposure</p></div><div class="index-card"><strong>05</strong><p>Operator network</p></div></div></section>
  <section class="page home-sectors"><div class="section-label"><span>04 / What we build</span><span>Lanes in motion</span></div><h2 class="display home-section-title">What We Build</h2><div class="cards sector-cards"><article class="feature-card"><h3>Trading Desk</h3><p>Process, execution, extraction.</p></article><article class="feature-card"><h3>Media & Motion</h3><p>High-visual culture into service and signal.</p></article><article class="feature-card"><h3>Brand Incubation</h3><p>Make the idea useful and ownable.</p></article><article class="feature-card"><h3>Real Estate</h3><p>Physical value with new rails.</p></article><article class="feature-card"><h3>Fashion</h3><p>Culture with a supply chain.</p></article><article class="feature-card"><h3>Collectibles & Watches</h3><p>Objects with provenance and attention.</p></article></div><p class="desk-line">We do not just talk markets. We build lanes people can enter.</p></section>
  <section class="page cream-band tokenization-block"><div class="split"><div><div class="eyebrow">05 / Tokenization</div><h2 class="display" style="font-size:clamp(64px,10vw,130px);margin:30px 0 0">The next<br>rail.</h2></div><div><p class="lede">Gold. Oil. Railroads. Internet.</p><p class="body-copy">Now ownership goes on-chain. Tokenization is the next infrastructure wave.</p><p class="body-copy">Gami Boyz / Kurogami is how operators enter early.</p></div></div></section>
  <section class="page access-summary"><div class="split"><div><div class="eyebrow">06 / Access</div><h2 class="display" style="font-size:clamp(70px,12vw,160px);margin:25px 0">Enter the<br>network.</h2></div><div><p class="body-copy">Token and access are coming through the same structure. This is membership into an operator system, not a random mint.</p><p class="body-copy">Start with the signal. Earn the room.</p>${button('Request Access', '#/join')}${button('See Access Paths', '#/access', true)}</div></div></section>
  ${homeGallery()}
  <section class="page cream-band"><div class="split"><div><div class="eyebrow">Last call</div><h2 class="display" style="font-size:clamp(70px,12vw,160px);margin:25px 0">GET IN<br>FORMATION.</h2></div><div><p class="lede">Access is earned. The request window is open.</p>${button('Request Access', '#/join')}</div></div></section>`;
}

function club() { return `<section class="page">${header('Inside / GB club', 'The Boyz', 'This is the brotherhood room. Culture, loyalty, and motion over performance theater.')}<div class="cards"><article class="feature-card"><span class="number">01</span><h3>Operators</h3><p>People who make the move before the room catches up.</p></article><article class="feature-card"><span class="number">02</span><h3>Creators</h3><p>Artists, builders, tastemakers. The ones making the signal louder.</p></article><article class="feature-card"><span class="number">03</span><h3>Street-to-<br>finance movers</h3><p>Cultural fluency with an operator's instinct.</p></article><article class="feature-card"><span class="number">04</span><h3>Presence</h3><p>Club events, pop-ups, and showing up in real life.</p></article></div></section><div class="ticker"><span>GAMI BOYZ MOVE TOGETHER <b>✦</b> CULTURE IS THE CURRENCY <b>✦</b> </span></div>`; }
function access() { return `<section class="page">${header('Threshold / 002', 'Access', 'A key to the room. Membership is simple: show signal, hold the line, move with the club.')}<div class="tier-grid"><article class="tier"><h3>Runner</h3><p>You're on the radar. Get the signal and find your way to the room.</p><span class="eyebrow">Entry / Signal</span></article><article class="tier"><h3>Boyz</h3><p>Core membership. Club access, drops, events, and the full transmission.</p><span class="eyebrow">Entry / Member</span></article><article class="tier"><h3>Inner Circle</h3><p>For the ones moving the room forward. Invite only. Keep it locked.</p><span class="eyebrow">Entry / Invite</span></article></div><div class="panel dark"><h2>Access is earned.</h2><p>Hold-to-enter access may connect to a token or club key when the rail is live. No shortcuts. No guarantees.</p>${button('Request Access', '#/join')}</div></section>`; }
function gallery() { return `<section class="page">${header('Visual archive / 003', 'Gallery', 'Cut-ups from the movement. Red signal, black ink, living symbols.')}<div class="art-grid"><div class="art-panel tall"><img src="${artOne}" alt="Fragmented illustrated character with glitch cuts" /><span class="art-note">Character study / 01</span><b class="art-type">EYE<br>ON</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-41-53.jpg" alt="Red masked illustrated figure" /><span class="art-note">Chain language</span><b class="art-type">LINK</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-39-18.jpg" alt="Split portrait illustration" /><span class="art-note">Street myth / 03</span><b class="art-type">RAW</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-40-50.jpg" alt="Illustrated food and culture scene" /><span class="art-note">Signal / 04</span><b class="art-type">TABLE</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-39-09.jpg" alt="Illustrated food still life" /><span class="art-note">No spectators</span><b class="art-type">MOVE</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-41-23.jpg" alt="Illustrated landscape emblem" /><span class="art-note">World study</span><b class="art-type">▲</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-39-56.jpg" alt="Illustrated pink character" /><span class="art-note">Character study / 07</span><b class="art-type">PINK</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-40-42.jpg" alt="Illustrated portrait close-up" /><span class="art-note">Portrait / 08</span><b class="art-type">LOOK</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-39-35.jpg" alt="Illustrated character composition" /><span class="art-note">Study / 09</span><b class="art-type">FORM</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-39-45.jpg" alt="Illustrated culture composition" /><span class="art-note">Study / 10</span><b class="art-type">ROOT</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-40-04.jpg" alt="Illustrated character and symbol" /><span class="art-note">Study / 11</span><b class="art-type">SIGNAL</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-41-02.jpg" alt="Illustrated scene from the movement" /><span class="art-note">Study / 12</span><b class="art-type">SCENE</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-41-12.jpg" alt="Illustrated portrait and mark" /><span class="art-note">Study / 13</span><b class="art-type">MARK</b></div><div class="art-panel"><img src="${artTwo}" alt="Pyramid, clouds, hand, and all-seeing eye" /><span class="art-note">Pyramid study / 14</span><b class="art-type">EYE</b></div><div class="art-panel"><img src="assets/photo_2026-09-01_21-42-02.jpg" alt="Gami Boyz emblem artwork" /><span class="art-note">Emblem / 15</span><b class="art-type">GB</b></div></div></section>`; }
function token() { return `<section class="page">${header('Token rail / 004', 'Token', 'No live token is being claimed here. When the rail is real, the official signal will land in this room first.')}<div class="panel dark"><div class="eyebrow">Status / Coming</div><h2>Token rail coming.</h2><p>There is no official contract address or buy link to share right now. Ignore fake Gami Boyz tokens, DMs, and promises of returns.</p><div class="btns">${button('Back to Club', '#/club', true)}</div></div></section>`; }
function join() { return `<section class="page"><div class="split">${header('Request / 005', 'Join', 'Tell us who you are. Club access is selective.') }<form class="form" id="join-form"><label>Name / handle<input name="name" required placeholder="your signal" /></label><label>Telegram / IG<input name="social" required placeholder="@handle" /></label><label>City<input name="city" placeholder="where you move" /></label><label>Why do you want in?<textarea name="why" required placeholder="keep it real"></textarea></label><label>Proof / ref note <span>(optional)</span><input name="proof" placeholder="who can vouch?" /></label><button class="btn" type="submit">Send Request <span>↗</span></button></form><div class="panel success" id="join-success"><div class="eyebrow">Transmission received</div><h2>Request received.</h2><p>Club access is selective. Watch your signal.</p></div></div></section>`; }
function members() { return `<section class="page"><div class="gate"><div class="eyebrow">Private room / 006</div><h1 class="display" style="font-size:clamp(85px,17vw,180px);margin:30px 0">Members<br>only.</h1><p class="lede">Password gate placeholder. The room opens when the signal is right.</p><form class="form" id="gate-form"><label>Club key<input type="password" placeholder="enter key" required /></label><button class="btn" type="submit">Enter Room <span>↗</span></button></form><div class="panel dark" id="member-room" style="display:none"><h2>Welcome inside.</h2><div class="announcement"><strong>Announcements</strong><small>Next transmission pending</small></div><div class="announcement"><strong>Art drops</strong><small>Archive / Locked</small></div><p>Access status: <b>Boyz / active</b></p></div></div></section>`; }

const routes = { '/':home, '/club':club, '/access':access, '/gallery':gallery, '/token':token, '/join':join, '/members':members };
function bindGalleryLinks() { document.querySelectorAll('.art-panel img').forEach(image => { const link = document.createElement('a'); link.className = 'art-link'; link.href = artistInstagram; link.target = '_blank'; link.rel = 'noreferrer noopener'; link.setAttribute('aria-label', `View artwork by Tokeyodraws on Instagram`); image.replaceWith(link); link.append(image); }); }
function render() { const path = window.location.hash.replace('#','') || '/'; document.body.dataset.route = path === '/' ? 'home' : path.slice(1); app.innerHTML = (routes[path] || home)(); bindGalleryLinks(); app.focus(); window.scrollTo(0,0); bindForms(); }
function bindForms() { const form = document.querySelector('#join-form'); if (form) form.addEventListener('submit', event => { event.preventDefault(); form.style.display='none'; document.querySelector('#join-success').classList.add('show'); }); const gate = document.querySelector('#gate-form'); if (gate) gate.addEventListener('submit', event => { event.preventDefault(); gate.style.display='none'; document.querySelector('#member-room').style.display='block'; }); }
window.addEventListener('hashchange', render); render();
